<?php
/* 
 * Generated by Ravikumar Pulusu 
 * www.tayatech.com
 */
 
class Home extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Restaurant');
    }

 
	public function index($pagename="index")
	{
//		echo $pagename; exit;
		switch ($pagename)
		{
			case 'index':
				 $this->load->view('web/home-web');
				break;
			case "about":
			$p_id =1;
			 $data['pages'] = $this->Restaurant->get_pages($p_id);
				 $this->load->view('web/about-web',$data);
				break;		
			case "careers":
				$data['careers'] = $this->Restaurant->Getcareers();
				 $this->load->view('web/careers-web',$data);
				break;		
			case "Offers-terms":
			$p_id =5;
			 $data['pages'] = $this->Restaurant->get_pages($p_id);
				 $this->load->view('web/offers_terms-web',$data);
				break;		
			case "refund-policy":
			$p_id =8;
			 $data['pages'] = $this->Restaurant->get_pages($p_id);
				 $this->load->view('web/refund-policy-web',$data);
				break;
			case "partner-with-us":
			if(!empty($_POST)){
	     
			$userData = array(
                'partner' => strip_tags($this->input->post('partner')),
                'city' => strip_tags($this->input->post('city')),
                'address' => strip_tags($this->input->post('address')),
				'title' => $this->input->post('title'),
				'first_name' => strip_tags($this->input->post('first_name')),
				'last_name' => strip_tags($this->input->post('last_name')),
				'phone' => strip_tags($this->input->post('phone')),
				'email' => strip_tags($this->input->post('email')),
				'num_locations' => strip_tags($this->input->post('num_locations')),
				'cuisine_type' => strip_tags($this->input->post('cuisine_type')),
				'weekly_orders' => strip_tags($this->input->post('weekly_orders')),
				'offer_delivery' => strip_tags($this->input->post('offer_delivery')),
				
            );
		$insert = $this->Restaurant->Insertpartners($userData);
		if($insert){
			$subject="Strokks Partner Us";	
		$mail=array('ravip@tayatech.com','info@dhaaksh.com','storkks2018@gmail.com');
		$message="Recieved a New Partner Request";
		
		
		$this->load->library('email');
		$this->email->set_newline("\r\n");
		$this->email->set_header('MIME-Version', '1.0; charset=utf-8'); 
		$this->email->set_header('Content-type', 'text/html'); 

		$this->email->from('storkks2018@gmail.com', 'Strokks');
		$this->email->to($mail);
		
		$this->email->subject($subject);
		$this->email->message($message);
	
		$emailll = $this->email->send();
		
		$mailto = $this->input->post('email');
		$message1="Recieved your request will get back to you soon";
		$this->email->from('storkks2018@gmail.com', 'Strokks');
		$this->email->to($mailto);
		$this->email->subject($subject);
		$this->email->message($message1);
		$emailll = $this->email->send();
		
		redirect('partner-with-us?msg=s');
		}
	}
				 $this->load->view('web/partner-web');
				break;		
			case "privacy-policy":
					$p_id =3;
					$data['pages'] = $this->Restaurant->get_pages($p_id);
					$this->load->view('web/privacy-policy-web',$data);
				break;		
			case "terms-and-conditions":
					$p_id =4;
					$data['pages'] = $this->Restaurant->get_pages($p_id);
					$this->load->view('web/terms_and_conditions',$data);
				break;		
			case "Blog":
				$this->load->view('web/blog-web');
				break;
				case "Support":
				 $this->load->view('web/support-web');
				break;
			case "My-account":
				$c_id =$this->session->userdata('customer_id');
				$data['orders'] = $this->Restaurant->getOrdersbyuser($c_id);
				$data['favourites'] = $this->Restaurant->get_favsbyuser($c_id);
				$data['address'] = $this->Restaurant->getuser_address($c_id);
				$data['promocodes'] = $this->Restaurant->getPromocodeRowsbyuser();
				$data['user'] = $this->Restaurant->getusers($c_id);
				$this->load->view('web/my-account-web',$data);
				break;		
			case "help-and-support":
				
				$p_id =2;
				$data['faq'] = $this->Restaurant->get_pages($p_id);
				$pid =7;
				$data['general'] = $this->Restaurant->get_pages($pid);
				$this->load->view('web/Help-and-support',$data);
			break;			
			default:
				$var = array('heading'=>'404 Page Not Found','message'=>'The page you requested was not found');
				$view = $this->load->view('errors/error_404', $var, true);
			    echo $view;
			    exit();
				break;
		}
	}
	function get_shopbyfav($rid){
	return $faves = $this->Restaurant->getShopRows($rid);
	}
	function getShops($id){
	return $data['shops'] = $this->Restaurant->getShopRows($id);
	}
	function getAddressbyorder($id){
	return $data['address'] = $this->Restaurant->getuser_address_byorder($id);
	}
	function Cuisine_nameby($id){
	$dataaa = $this->Restaurant->getCuisinesRows($id);	
	echo $dataaa['name']; //exit;
	}

}
