<?php
/* 
 * Generated by Ravikumar Pulusu 
 * www.tayatech.com
 */
 
class Profile extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Restaurant');
    }

 
	public function index($id = "")
	{
		if($id == ""){
			redirect('');
		}
		$this->load->library("cart");
		$cartdt = $this->cart->contents();
		if(!empty($cartdt)){
		 foreach ($this->cart->contents() as $items) {
			 $itid = $items['id'];
		 }
		 
		$rids = $this->Restaurant->getproducts($itid);
		$data['ridss']=  $rids['restaurant_id'];
		$data['checkout']=  $this->cart->contents();
		
		}
		$data['timeweb'] = $this->Restaurant->getShoptimings($id);
			$data['timings'] = $this->Restaurant->getShopRowsweb($id);
			$data['category'] = $this->Restaurant->getCategorybyshop($id);
			$data['shops'] = $this->Restaurant->getShopRows($id);
			//$data['products_lst'] = $this->Restaurant->get_products($id);
			$this->load->view('web/profile-web',$data);
	}
	public function products($id,$rid)
	{
		return $products = $this->Restaurant->getproductsby_cat_rest($id,$rid);
	}
	public function Cuisines($cat)
	{
		return $Cuisines = $this->Restaurant->getCuisinesRows($cat);
	}
	public function getAddonsbycategory($value)
	{
	return $addons = $this->Restaurant->getAddonsbycategory($value);
	}
	public function getAddonsbycat($value)
	{
	return $addons = $this->Restaurant->getAddonsbycat($value);
	}
	public function Addonsbyproduct($valueee,$catadnsid)
	{
	return $addons = $this->Restaurant->getAddonsbyproduct($valueee,$catadnsid);
	}
	
	

}
