<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vh_usr_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vh_usr by ID
     */
    function get_vh_usr($ID)
    {
        return $this->db->get_where('vh_usr',array('ID'=>$ID))->row_array();
    }
    function email_exists($params)
	{
//		echo $params; exit;
	$this->db->where('EMAIL', $params);
	$query = $this->db->get('vh_usr');
	return $query->num_rows();
	}
    /*
     * Get all vh_usr count
     */
    function get_all_vh_usr_count()
    {
        $this->db->from('vh_usr');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all vh_usr
     */
    function get_all_vh_usr($params = array())
    {
        $this->db->order_by('ID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('vh_usr')->result_array();
    }
        
    /*
     * function to add new vh_usr
     */
    function add_vh_usr($params)
    {
        $this->db->insert('vh_usr',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vh_usr
     */
    function update_vh_usr($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('vh_usr',$params);
    }
    
    /*
     * function to delete vh_usr
     */
    function delete_vh_usr($ID)
    {
        return $this->db->delete('vh_usr',array('ID'=>$ID));
    }
}
