<?php
/* 
 * Generated by Ravikumar pulusu 
 *
 */
 
class Admin_login extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Restaurant');
		$this->load->library('session');
				
    }
	function index(){
//echo '<pre>'; print_r($_POST); echo '</pre>';	 exit;
	if(!empty($_POST)){
	$usn = $this->input->post('email');
	$pwd = $this->input->post('password');
	$query = $this->Restaurant->Admin_login($usn,$pwd);
//	print_r($query); exit;
	$admin_id = $query['id'];
	$admin_name = $query['name'];
	$admin_email = $query['email'];
	//$sess_array = array('id' => $query['id'],'shopname' => $query['name'],'email'=> $query['email']);
	$this->session->set_userdata('admin', $admin_id);
	$this->session->set_userdata('adminname', $admin_name);
	$this->session->set_userdata('adminemail', $admin_email);
	$session_admin = $this->session->userdata('admin');  
	if($session_admin){
		redirect('Admin');
	}
	}
        $this->load->view('admin-login');
    }
	function logout(){
      $user_data = $this->session->all_userdata();

    $this->session->sess_destroy();
    redirect('Shop');
    }
	
	}