<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Home extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        //$this->load->model('Vh_usr_model');
    }

    function index()
    {
//echo "testing homw"; exit;
		
        $this->load->view('homev1');
    }

}
