<?php
/* 
 * Generated by Ravikumar pulusu 
 *
 */
 
class Shop extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Restaurant');
		$this->load->library('session');

		
    }	
	function UploadImage(){
				$config['upload_path'] = 'uploads/images';
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
				$config['file_name'] = time().$_FILES['avatar']['name']; 
                $this->load->library('upload',$config);
                $this->upload->initialize($config);
                if($this->upload->do_upload('avatar')){
                    $uploadData = $this->upload->data();
                    $picture = $uploadData['file_name'];
                }else{
                   echo $picture = 'not upload'; exit; 
                }
				return $picture;

	}
	function index(){
		redirect('Shop/dashboard');
    }
    function dashboard(){
		
	if(!empty($_POST)){
	$usn = $this->input->post('email');
	$pwd = $this->input->post('password');
	$query = $this->Restaurant->Shop_login($usn,$pwd);
	$shop_id = $query['id'];
	$shop_name = $query['name'];
	$sess_array = array('id' => $query['id'],'shopname' => $query['name'],'email'=> $query['email']);
	$this->session->set_userdata('Shopid', $shop_id);
	$this->session->set_userdata('Shopname', $shop_name);
	$session_shop = $this->session->userdata['Shopid']; // exit;
	}
	if($this->session->userdata['Shopid']== null ){ redirect('Shop_login');}
	$this->load->view('shop/Shop-dashboard');
	}
	function Dispatcher(){
		if($this->session->userdata['Shopid']== null ){ redirect('Shop_login');}	
		$this->load->view('shop/Shop-dashboard');
	}
	function Addcategory(){
	if(!empty($_POST)){
	if(!empty($_FILES['avatar']['name'])){
		$picture = $this->UploadImage(); //exit;
		}else{
			$picture = 	$this->input->post('avatarimage');
		}
		$userData = array(
                'cat_name' => strip_tags($this->input->post('name')),
                'cat_description' => strip_tags($this->input->post('description')),
			    'restaurant_id' => strip_tags($this->input->post('shop_id')),
                'status' => strip_tags($this->input->post('status')),
                'cat_order' => strip_tags($this->input->post('position')),
                'cat_image' =>$picture
                );
		$insert = $this->Restaurant->InsertCategory($userData);
		if($insert){
			redirect('Shop/Category');
			}else{
				echo "failed Create"; exit;
			}
	}
	$this->load->view('shop/add-categorie');
	}
	function Category(){
		
	if($this->session->userdata['Shopid']== null ){ redirect('Shop_login');}	
	$data['category'] = $this->Restaurant->getCategory();	
	$this->load->view('shop/list-categories',$data);
	}
	function EditCategory($id){
	$data['category'] = $this->Restaurant->getCategory($id);		
	if(!empty($_POST)){
		//echo '<pre>'; print_r($_POST); echo '</pre>';	 exit;
	if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
			}else{
				$picture = '';
			}
	$userData = array(
                'cat_name' => strip_tags($this->input->post('name')),
                'cat_description' => strip_tags($this->input->post('description')),
                'status' => strip_tags($this->input->post('status')),
                'cat_image' =>$picture
            );
	$update = $this->Restaurant->UpdateCategory($userData,$id);
		if($update){
			redirect('Shop/Category');
		}else{
		echo "failed Create"; exit;
		}
	}
	$this->load->view('shop/add-categorie',$data);
	}
	function Categorydelete($id){
		$efected = $this->Restaurant->Catdelete($id);
		if($efected){
			 $this->session->set_flashdata('catdelete','Succussfully  Category deleted'); 
		}
		redirect('shop/Category');
	}
	function Addons(){
		$data['addons'] = $this->Restaurant->getAddons();	
		$this->load->view('shop/list-addons',$data);
	}
	function Addondelete($id){
		$efected = $this->Restaurant->Addondelete($id);
		if($efected){
		 $this->session->set_flashdata('addondelete','Succussfully  Addon deleted'); 
		}
		redirect('shop/Addons');
	}
	function EditAddon($id){
	$data['addons'] = $this->Restaurant->getAddons($id);		

	if(!empty($_POST)){
	$userData = array(

                'addon_name' => strip_tags($this->input->post('name')),
                'status' => strip_tags($this->input->post('status'))
            );
	$update = $this->Restaurant->UpdateAddons($userData,$id);
	if($update){
		$this->session->set_flashdata('addondelete','Succussfully  Addon Updated'); 
		redirect('Shop/Addons');
	}else{
		$this->session->set_flashdata('addondelete','Failed  Addon Updated'); 
		//echo "failed Create"; exit;		
	 }
	}
		$this->load->view('shop/add-Addons',$data);		
	}
	function AddAddons(){

	
	if(!empty($_POST)){
	
	$userData = array(
                'restaurant_id' => strip_tags($this->input->post('shop_id')),
                'restaurant_name' => strip_tags($this->input->post('shop_name')),
                'addon_name' => strip_tags($this->input->post('name')),
                'status' => strip_tags($this->input->post('status'))
            );
	$Insert = $this->Restaurant->InsertAddons($userData);
	if($Insert){
		redirect('Shop/Addons');
	}else{
		echo "failed Create"; exit;		
	 }
	}
		$this->load->view('shop/add-Addons');
	}
	function Products(){
	if($this->session->userdata['Shopid']== null ){ redirect('Shop_login');}		
		$data['products'] = $this->Restaurant->getproducts();	
		$this->load->view('shop/list-Products',$data);
	}
	function AddProducts(){
	if($this->session->userdata['Shopid']== null ){ redirect('Shop_login');}		
	if(!empty($_POST)){
	
	if(!empty($_FILES['avatar']['name'])){
	$picture = $this->UploadImage();	
	}
	if(!empty($_FILES['avatar']['name'])){
	$picture = $this->UploadImage();	
	}
	$userData = array(
                'product_name' => strip_tags($this->input->post('name')),
                'description' => strip_tags($this->input->post('description')),
                'category' => strip_tags($this->input->post('category')),
                'status' => strip_tags($this->input->post('status')),
                'product_Order' => strip_tags($this->input->post('product_position')),
                'is_featured' => strip_tags($this->input->post('featured')),
                'featured_position' => strip_tags($this->input->post('featured_position')),
                'price' => strip_tags($this->input->post('price')),
                'discount' => strip_tags($this->input->post('discount')),
                'discount_type' => strip_tags($this->input->post('discount_type')),
                'addons' =>implode(",",$_POST['addons']),
                'addons_price' =>implode(",",$_POST['addons_price']),
                'product_image' =>$picture,
                'featured_image' =>$picture
            );
	$Insert = $this->Restaurant->InsertProduct($userData);
	if($Insert){
		redirect('Shop/Products');
	}else{
		echo "failed Create"; exit;		
		 }
	}
		$this->load->view('shop/add-product');
	}	
	function Profile(){
		$shopid =	$this->session->userdata['Shopid']; 
		$data['profile'] = $this->Restaurant->getShopRows($shopid);	
	if(!empty($_POST)){
//	echo '<pre>'; print_r($_POST); echo '</pre>';	 exit;	
	if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
						}else{
						$picture =	strip_tags($this->input->post('avatar'));
						}
				$userData = array(
                'name' => strip_tags($this->input->post('name')),
                'Cuisine' => implode(",",$_POST['cuisine_id']),
                'phone' => strip_tags($this->input->post('phone')),
                'email' => strip_tags($this->input->post('email')),
                'password' => md5($this->input->post('password')),
                'resturant_opens' => $_POST['hours_opening']['ALL'],
                'resturant_close' => $_POST['hours_closing']['ALL'],
                'pure_veg' =>  strip_tags($this->input->post('pure_veg')),
                'shop_logo' =>  $picture,
                'min_amount' =>  strip_tags($this->input->post('offer_min_amount')),
                'offer_percentage' =>  strip_tags($this->input->post('offer_percent')),
                'estimated_delivery_time' =>  strip_tags($this->input->post('estimated_delivery_time')),
                'description' =>  strip_tags($this->input->post('description')),
                'address' =>  strip_tags($this->input->post('address')),
                'latitude' =>  strip_tags($this->input->post('latitude')),
                'longitude' =>  strip_tags($this->input->post('longitude')),
                'status' =>  strip_tags($this->input->post('status')),
                'everyday' =>  strip_tags($this->input->post('everyday'))         
            );
		//	print_r($userData); exit;
		 $update = $this->Restaurant->updateShop($userData,$shopid);
		if($update){
			redirect('Shop/profile');
			}else{
			echo "failed Create"; exit;
			}
	}
		
//		$data['people'] = $this->Restaurant->getShopRows($shopid);
		$data['csns'] = $this->Restaurant->getCuisinesRows();
		//$this->load->view('addrestaurant',$data);
		$this->load->view('shop/shop-profile',$data);
	}
	function Deliveries(){
		$this->load->view('shop/list-deliveries');
	}
	

	function Users(){
		$data['pages'] = $this->Restaurant->getusers();
		$this->load->view('users-list', $data);
	}
	function EditUser($id){
		$data['people'] = $this->Restaurant->getusers($id);
		
	if(!empty($_POST)){
	        if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
			}else{
				
			$picture = $this->input->post('avatarimage');	
			}
		$userData = array(
                'first_name' => strip_tags($this->input->post('name')),
                'phone' => strip_tags($this->input->post('phone_number')),
                'email' => strip_tags($this->input->post('email')),
                //'password' => md5($this->input->post('password')),
                'profile_image' => $picture,
                'country_code' =>  strip_tags($this->input->post('country_code')),
               
            );
		$insert = $this->Restaurant->UpdateUsers($userData,$id);
		if($insert){
			//echo "Thanks for register will get back to you soon".$insert; exit;
			redirect('Admin/Users');
		}else{
			echo "failed Create"; exit;
		}
		
	}	
	$this->load->view('add-user', $data);}
	function AddUser(){
	if(!empty($_POST)){
	        if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
			}
			$userData = array(
                'first_name' => strip_tags($this->input->post('name')),
                'phone' => strip_tags($this->input->post('phone_number')),
                'email' => strip_tags($this->input->post('email')),
                'password' => md5($this->input->post('password')),
                'profile_image' => $picture,
                'country_code' =>  strip_tags($this->input->post('country_code')),
               
            );
		$update = $this->Restaurant->InsertUsers($userData);
		if($update){
			redirect('Admin/Users');
		}else{
			echo "failed Create"; exit;
		}
	}
	$this->load->view('add-user');
	}
	


}
