<?php
/* 
 * Generated by Ravikumar Pulusu 
 * www.tayatech.com
 */
 
class Profile extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Restaurant');
    }

 
	public function index($id = "")
	{
	
		$data['category'] = $this->Restaurant->getCategorybyshop($id);
		 $data['shops'] = $this->Restaurant->getShopRows($id);
		 $this->load->view('web/profile-web',$data);
	}
	public function products($id)
	{
		return $products = $this->Restaurant->getproductsbycat($id);
	}
	

}
