<?php
/* 
 * Generated by Ravikumar pulusu 
 *
 */
 
class Admin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Restaurant');
    }

    function index(){
		$session_admin = $this->session->userdata('admin');
	if($session_admin){

		   $this->load->view('admin_dashboard');
	}else{
		redirect('Admin_login');
	}
//        $this->load->view('admin_dashboard');
    }

	
	function UploadImage(){
				$config['upload_path'] = 'uploads/images';
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
                $config['file_name'] = time().$_FILES['avatar']['name'];
                
                $this->load->library('upload',$config);
                $this->upload->initialize($config);
                if($this->upload->do_upload('avatar')){
                    $uploadData = $this->upload->data();
                    $picture = $uploadData['file_name'];
                }else{
                   echo $picture = 'not upload'; exit; 
                }
				return $picture;

	}
	function Addons($id){
	$data['addons'] = $this->Restaurant->getRAddons($id);	
//	print_r($data); exit;
	$this->load->view('rlist-addons',$data);
		
	}
	function Shopname($id){
	$dataaa = $this->Restaurant->getShopname($id);	
	echo $dataaa; //exit;
	}
	function D_boyname($id){
	$dataaa = $this->Restaurant->getdboyname($id);	
	echo $dataaa; //exit;
	}	
	function Users(){
		$data['pages'] = $this->Restaurant->getusers();
		$this->load->view('users-list', $data);
	}
	function EditUser($id){
		$data['people'] = $this->Restaurant->getusers($id);
		
	if(!empty($_POST)){
	        if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
			}else{
				
			$picture = $this->input->post('avatarimage');	
			}
		$userData = array(
                'first_name' => strip_tags($this->input->post('name')),
                'phone' => strip_tags($this->input->post('phone_number')),
                'email' => strip_tags($this->input->post('email')),
                //'password' => md5($this->input->post('password')),
                'profile_image' => $picture,
                'country_code' =>  strip_tags($this->input->post('country_code')),
               
            );
		$insert = $this->Restaurant->UpdateUsers($userData,$id);
		if($insert){
			//echo "Thanks for register will get back to you soon".$insert; exit;
			redirect('Admin/Users');
		}else{
			echo "failed Create"; exit;
		}
		
	}	
	$this->load->view('add-user', $data);}
	function AddUser(){
	if(!empty($_POST)){
	        if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
			}
			$userData = array(
                'first_name' => strip_tags($this->input->post('name')),
                'phone' => strip_tags($this->input->post('phone_number')),
                'email' => strip_tags($this->input->post('email')),
                'password' => md5($this->input->post('password')),
                'profile_image' => $picture,
                'country_code' =>  strip_tags($this->input->post('country_code')),
               
            );
		$update = $this->Restaurant->InsertUsers($userData);
		if($update){
			redirect('Admin/Users');
		}else{
			echo "failed Create"; exit;
		}
	}
	$this->load->view('add-user');
	}
	function Notice(){
		$data['pages'] = $this->Restaurant->getnotices();
		$this->load->view('noticeboard_list', $data);
	}
	
	function EditNotice($id){
		$data['pages'] = $this->Restaurant->getnotices($id);
		$data['people'] = $this->Restaurant->getPeopleRows();
		if(!empty($_POST)){
		$userData = array(
                'transporter_id' => strip_tags($this->input->post('transporter_id')),
                'title' => strip_tags($this->input->post('title')),
                'notice' => strip_tags($this->input->post('notice')),
                'note' => strip_tags($this->input->post('note'))
                              
        );
		$update = $this->Restaurant->UpdateNotice($userData,$id);
		if($update){
		redirect('Admin/Notice');
		}else{
			echo "failed Create"; exit;
		}
	}
	$this->load->view('add-noticeboard',$data);
	}
	function Addnotice(){
		$data['people'] = $this->Restaurant->getPeopleRows();
		
	if(!empty($_POST)){
		//echo '<pre>'; print_r($_POST); echo '</pre>';	 exit;
		$userData = array(
                'transporter_id' => strip_tags($this->input->post('transporter_id')),
                'title' => strip_tags($this->input->post('title')),
                'notice' => strip_tags($this->input->post('notice')),
                'note' => strip_tags($this->input->post('note'))
                              
        );
		$insert = $this->Restaurant->InsertNotice($userData);
		if($insert){
		redirect('Admin/Notice');
		}else{
			echo "failed Create"; exit;
		}
	}
	$this->load->view('add-noticeboard', $data);
	}
	function CustomPush(){
		
	if(!empty($_POST)){
	//	echo '<pre>'; print_r($_POST); echo '</pre>';	 exit;
		$userData = array(
                'send_to' => strip_tags($this->input->post('send_to')),
                'user_condition' => strip_tags($this->input->post('user_condition')),
                'user_active' => strip_tags($this->input->post('user_active')),
                'user_rides' => strip_tags($this->input->post('user_rides')),
                'user_amount' => strip_tags($this->input->post('user_amount')),
                'user_location' => strip_tags($this->input->post('user_location')),
                'provider_condition' => strip_tags($this->input->post('provider_condition')),
                'provider_active' => strip_tags($this->input->post('provider_active')),
                'provider_rides' => strip_tags($this->input->post('provider_rides')),
                'provider_amount' => strip_tags($this->input->post('provider_amount')),
                'message' => strip_tags($this->input->post('message')),
                'schedule_date' => strip_tags($this->input->post('schedule_date')),
                'schedule_time' => strip_tags($this->input->post('schedule_time'))
                              
        );
		$insert = $this->Restaurant->InsertCustomeNotice($userData);
		if($insert){
				//echo "Thanks for register will get back to you soon".$insert; exit;
				redirect('Admin/Notice');
			}else{
				echo "failed Create"; exit;
			}
	}
	$this->load->view('custom-push');
	}
	function RestaurentBanners(){
		$data['pages'] = $this->Restaurant->getRestaurentBanner();
		$this->load->view('rbanners_list', $data);
	}
	
	function EditRBanner($id){
	$data['pages'] = $this->Restaurant->getRestaurentBanner($id);	
	$data['shops'] = $this->Restaurant->getShopRows();

		if(!empty($_POST)){
			 if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
				}else{
				$picture = 	$this->input->post('avatarimage');
				}
		$userData = array(
                'shop_id' => strip_tags($this->input->post('shop_id')),
                'product_id' => strip_tags($this->input->post('product_id')),
                'position' => strip_tags($this->input->post('position')),
                'banner' =>$picture,
                'status' => strip_tags($this->input->post('status'))
                              
        );
		 $update = $this->Restaurant->UpdateBanner($userData,$id);
		if($update){
						redirect('admin/RestaurentBanners');
			}else{
				echo "failed Create"; exit;
			}
	}
	$this->load->view('add-rbanners',$data);
		
	}
	function AddRestaurentBanner(){
		
	if(!empty($_POST)){
			 if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
				//echo $picture; exit;
			}
		$userData = array(
                'shop_id' => strip_tags($this->input->post('shop_id')),
                'product_id' => strip_tags($this->input->post('product_id')),
                'position' => strip_tags($this->input->post('position')),
                'banner' =>$picture,
                'status' => strip_tags($this->input->post('status'))
                              
        );
		 $insert = $this->Restaurant->InsergetRestaurentBanner($userData);
		if($insert){
				//echo "Thanks for register will get back to you soon".$insert; exit;
				redirect('admin/RestaurentBanners');
			}else{
				echo "failed Create"; exit;
			}
	}
	$this->load->view('add-rbanners');
	}	
	function Promocodes()
    {
		$data['pages'] = $this->Restaurant->getPromocodeRows();
		$this->load->view('promocodes_list', $data);
		
	}
	
	function EditPcode($id){
	$data['pages'] = $this->Restaurant->getPromocodeRows($id);
	if(!empty($_POST)){
			$userData = array(
                'promo_code' => strip_tags($this->input->post('promo_code')),
                'discount' => strip_tags($this->input->post('discount')),
                'promocode_type' => strip_tags($this->input->post('promocode_type')),
                'status' => strip_tags($this->input->post('status')),
                'expiration' =>  strip_tags($this->input->post('expiration'))
                              
        );
		 $update = $this->Restaurant->UpdatePromocode($userData,$id);
		if($update){
			redirect('admin/Promocodes');
			}else{
				echo "failed Create"; exit;
			}
	}
	$this->load->view('add-promocode',$data);
	}
	function AddPromocode(){
	if(!empty($_POST)){
			$userData = array(
                'promo_code' => strip_tags($this->input->post('promo_code')),
                'discount' => strip_tags($this->input->post('discount')),
                'promocode_type' => strip_tags($this->input->post('promocode_type')),
                'status' => strip_tags($this->input->post('status')),
                'expiration' =>  strip_tags($this->input->post('expiration'))
                              
        );
		 $insert = $this->Restaurant->InserPromocode($userData);
		if($insert){
				//echo "Thanks for register will get back to you soon".$insert; exit;
				redirect('admin/Promocodes');
			}else{
				echo "failed Create"; exit;
			}
	}
	$this->load->view('add-promocode');
	}
		function Deliveries(){
		$this->load->view('deliveries-list');
	}
	function shops()
    {
		 $data['pages'] = $this->Restaurant->getShopRows();
		 $this->load->view('restaurant_list', $data);
    }

	function EditShop($id){
	if(!empty($_POST)){
	if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
						}else{
				 $picture =	strip_tags($this->input->post('bavatar')); //exit;
						}
				$userData = array(
                'name' => strip_tags($this->input->post('name')),
                'Cuisine' => implode(",",$_POST['cuisine_id']),
                'phone' => strip_tags($this->input->post('phone')),
                'email' => strip_tags($this->input->post('email')),
                //'password' => md5($this->input->post('password')),
                'resturant_opens' => $_POST['hours_opening']['ALL'],
                'resturant_close' => $_POST['hours_closing']['ALL'],
                'pure_veg' =>  strip_tags($this->input->post('pure_veg')),
                'shop_logo' =>  $picture,
                'min_amount' =>  strip_tags($this->input->post('offer_min_amount')),
                'offer_percentage' =>  strip_tags($this->input->post('offer_percent')),
                'estimated_delivery_time' =>  strip_tags($this->input->post('estimated_delivery_time')),
                'description' =>  strip_tags($this->input->post('description')),
                'address' =>  strip_tags($this->input->post('address')),
                'latitude' =>  strip_tags($this->input->post('latitude')),
                'longitude' =>  strip_tags($this->input->post('longitude')),
                'status' =>  strip_tags($this->input->post('status')),
                'everyday' =>  strip_tags($this->input->post('everyday'))         
            );
		 $update = $this->Restaurant->updateShop($userData,$id);
		if($update){
				redirect('admin/shops');
			}else{
				echo "failed Create"; exit;
			}
	}
		
		$data['people'] = $this->Restaurant->getShopRows($id);
		$data['csns'] = $this->Restaurant->getCuisinesRows();
		$this->load->view('addrestaurant',$data);

	}	
	function Cuisines(){	
	$data['pages'] = $this->Restaurant->getCuisinesRows();
	$this->load->view('cuisines_list', $data);
	}
	function EditCuisines($id){
	$data['pages'] = $this->Restaurant->getCuisinesRows($id);
	if(!empty($_POST)){
		$userData = array(
                'name' => strip_tags($this->input->post('name'))
        );
		 $Update = $this->Restaurant->UpdateCuisines($userData,$id);
		if($Update){
				redirect('admin/Cuisines');
			}else{
				echo "failed Create"; exit;
			}
	}
		$this->load->view('add-cuisines',$data);	
	}
	function AddCuisines(){
	if(!empty($_POST)){
		$userData = array(
                'name' => strip_tags($this->input->post('name'))
        );
		 $insert = $this->Restaurant->InserCuisines($userData);
		if($insert){
				//echo "Thanks for register will get back to you soon".$insert; exit;
				redirect('admin/Cuisines');
			}else{
				echo "failed Create"; exit;
			}
	}
		$this->load->view('add-cuisines');
	}
	function DisputeManager(){
		 $data['people'] = $this->Restaurant->getManagerRows();
		 $this->load->view('dmanagerlist', $data);
	}
	function EditManager($id){
		 $data['people'] = $this->Restaurant->getManagerRows($id);
		if(!empty($_POST)){
		if(!empty($_FILES['avatar']['name'])){
			$picture = $this->UploadImage();}
			else{$picture = $this->input->post('avataredit');}
		$userData = array(
                'name' => strip_tags($this->input->post('name')),
                'phone' => strip_tags($this->input->post('phone')),
                'email' => strip_tags($this->input->post('email')),
               // 'password' => md5($this->input->post('password')),
                'profile_image' =>$picture
        );
		 $update = $this->Restaurant->ManagerUpdate($userData,$id);
		if($update){
				redirect('admin/DisputeManager');
			}else{
				echo "failed Create"; exit;
			}
	}
		$this->load->view('dispute-add',$data);
		
	}
	function AddManager(){
	if(!empty($_POST)){
		//		echo '<pre>'; print_r($_POST); echo '</pre>';	 exit;
		if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
				//echo $picture; exit;
			}
		$userData = array(
                'name' => strip_tags($this->input->post('name')),
                'phone' => strip_tags($this->input->post('phone')),
                'email' => strip_tags($this->input->post('email')),
                'password' => md5($this->input->post('password')),
                'profile_image' =>$picture
                              
        );
		 $insert = $this->Restaurant->Managerinsert($userData);
		if($insert){
				redirect('admin/DisputeManager');
			}else{
				echo "failed Create"; exit;
			}
	}
		$this->load->view('dispute-add');
	}
	function DeliveryPeople()
    {
		 $data['people'] = $this->Restaurant->getPeopleRows();
		 $this->load->view('deliverypeople_list', $data);
	}
	function EditPeople($id){
	if(!empty($_POST)){
	if(!empty($_FILES['avatar']['name'])){
		$picture = $this->UploadImage();
				}else{
		$picture = $this->input->post('avatarimage');					
				}
		$userData = array(
                'name' => strip_tags($this->input->post('name')),
                'phone' => strip_tags($this->input->post('phone_number')),
                'email' => strip_tags($this->input->post('email')),
                'profile_image' =>  $picture,
                'address' =>  strip_tags($this->input->post('address')),
                'latitude' =>  strip_tags($this->input->post('latitude')),
                'longitude' =>  strip_tags($this->input->post('longitude')),
                'country_code' =>  strip_tags($this->input->post('country_code')),
        );
		 $Update = $this->Restaurant->updatePeople($userData,$id);
		if($Update){
			redirect('admin/deliveryPeople');
			}else{
				echo "failed Create"; exit;
			}
	}
		
		$data['people'] = $this->Restaurant->getPeopleRows($id);
		$this->load->view('deliverypeople-add',$data);

	}	
	function AddPeople(){
	if(!empty($_POST)){
	//	echo '<pre>'; print_r($_POST); echo '</pre>';	 exit;
	 if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
						}
		$userData = array(
                'name' => strip_tags($this->input->post('name')),
                'phone' => strip_tags($this->input->post('phone_number')),
                'email' => strip_tags($this->input->post('email')),
                'password' => md5($this->input->post('password')),
                'profile_image' =>  $picture,
                'address' =>  strip_tags($this->input->post('address')),
                'latitude' =>  strip_tags($this->input->post('latitude')),
                'longitude' =>  strip_tags($this->input->post('longitude')),
                'country_code' =>  strip_tags($this->input->post('country_code')),
               
            );
		 $insert = $this->Restaurant->Peopleinsert($userData);
		if($insert){
				//echo "Thanks for register will get back to you soon".$insert; exit;
				redirect('admin/deliveryPeople');
			}else{
				echo "failed Create"; exit;
			}
	}
 $this->load->view('deliverypeople-add');
	}
	
	function Shopsdelete($id){
		$efected = $this->Restaurant->Shopdelete($id);
		redirect('admin/shops');
	}
	function DPeopleDelete($id){
		$efected = $this->Restaurant->Dpeopledelete($id);
		redirect('admin/DeliveryPeople');
	}
	function DManagerDelete($id){
		$efected = $this->Restaurant->DManagerdelete($id);
		redirect('admin/DisputeManager');
	}
	function CuisinesDelete($id){
		$efected = $this->Restaurant->cuisinesDelete($id);
		redirect('admin/Cuisines');
	}
	function PromocodesDelete($id){
		$efected = $this->Restaurant->PromoDelete($id);
		redirect('admin/Promocodes');
	}
	function BannerDelete($id){
		$efected = $this->Restaurant->BannerDelete($id);
		redirect('admin/RestaurentBanners');
	}
	function UserDelete($id){
		$efected = $this->Restaurant->UserDelete($id);
		redirect('admin/Users');
	}
	function Addshop()
    {	
	if(!empty($_POST)){
//			echo '<pre>'; print_r($_POST); echo '</pre>';	 			print_r($_POST['hours_closing']['ALL']); exit;
			if(!empty($_FILES['avatar']['name'])){
			$picture = $this->UploadImage();
			}
		$userData = array(
                'name' => strip_tags($this->input->post('name')),
                'Cuisine' => implode(",",$_POST['cuisine_id']),
                'phone' => strip_tags($this->input->post('phone')),
                'email' => strip_tags($this->input->post('email')),
                'password' => md5($this->input->post('password')),
                'resturant_opens' => $_POST['hours_opening']['ALL'],
                'resturant_close' => $_POST['hours_closing']['ALL'],
                'shop_logo' => $picture,
                'pure_veg' =>  strip_tags($this->input->post('pure_veg')),
                'min_amount' =>  strip_tags($this->input->post('offer_min_amount')),
                'offer_percentage' =>  strip_tags($this->input->post('offer_percent')),
                'estimated_delivery_time' =>  strip_tags($this->input->post('estimated_delivery_time')),
                'description' =>  strip_tags($this->input->post('description')),
                'address' =>  strip_tags($this->input->post('address')),
                'latitude' =>  strip_tags($this->input->post('latitude')),
                'longitude' =>  strip_tags($this->input->post('longitude')),
                'status' =>  strip_tags($this->input->post('status')),
                'everyday' =>  strip_tags($this->input->post('everyday')),
            
            );
		 $insert = $this->Restaurant->insert($userData);
		if($insert){
			//	echo "Thanks for register will get back to you soon";
				redirect('admin/shops');

			}else{
				echo "fail"; exit;
			}
	}			
       $data['csns'] = $this->Restaurant->getCuisinesRows();
	   $this->load->view('addrestaurant',$data);
    }

}
