<?php
/* 
 * Generated by Ravikumar Pulusu 
 * www.tayatech.com
 */
 
class Home extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Restaurant');
    }

 
	public function index($pagename="index")
	{
//		echo $pagename; exit;
		switch ($pagename)
		{
			case 'index':
				 $this->load->view('web/home-web');
				break;
			case "about":
				 $this->load->view('web/about-web');
				break;		
			case "careers":
				 $this->load->view('web/careers-web');
				break;		
			case "Offers-terms":
				 $this->load->view('web/offers_terms-web');
				break;		
			case "refund-policy":
				 $this->load->view('web/refund-policy-web');
				break;		
			case "privacy-policy":
				 $this->load->view('web/privacy-policy-web');
				break;		
			case "terms-and-conditions":
				 $this->load->view('web/terms_and_conditions');
				break;		
			case "Blog":
				 echo "<h1>Comming Soon</h1>"; exit;
				break;
				case "Support":
				 $this->load->view('web/support-web');
				break;
			case "My-account":
				$c_id =$this->session->userdata('customer_id');
				
				$data['favourites'] = $this->Restaurant->get_favsbyuser($c_id);
				$data['address'] = $this->Restaurant->getuser_address($c_id);
				$data['promocodes'] = $this->Restaurant->getPromocodeRows();
				$data['user'] = $this->Restaurant->getusers($c_id);
				$this->load->view('web/my-account-web',$data);
				break;		

			default:
				$var = array('heading'=>'404 Page Not Found','message'=>'The page you requested was not found');
				$view = $this->load->view('errors/error_404', $var, true);
			    echo $view;
			    exit();
				break;
		}
	}
	function get_shopbyfav($rid){
//echo $rid;
	return $faves = $this->Restaurant->getShopRows($rid);
//	print_r($data['shop']); 
	}
	function Cuisine_nameby($id){
	$dataaa = $this->Restaurant->getCuisinesRows($id);	
	echo $dataaa['name']; //exit;
	}

}
