<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pages extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Page_model');
    } 

    /*
     * Listing of pages
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('page/index?');
        $config['total_rows'] = $this->Page_model->get_all_pages_count();
        $this->pagination->initialize($config);

        $data['pages'] = $this->Page_model->get_all_pages($params);
        
        $data['_view'] = 'page/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new page
     */
	function view($pagename	)
    {
echo $pagename; exit;		
	}    
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'description' => $this->input->post('description'),
				'status' => $this->input->post('status'),
            );
            
            $page_id = $this->Page_model->add_page($params);
            redirect('pages/index');
        }
        else
        {            
            $data['_view'] = 'page/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a page
     */
    function edit($id)
    {   
        // check if the page exists before trying to edit it
        $data['page'] = $this->Page_model->get_page($id);
        
        if(isset($data['page']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'description' => $this->input->post('description'),
					'pid' => $this->input->post('pid'),
					'url' => $this->input->post('url'),
					'status' => $this->input->post('status'),
                );

                $this->Page_model->update_page($id,$params);            
                redirect('pages/index');
            }
            else
            {
                $data['_view'] = 'page/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The page you are trying to edit does not exist.');
    } 

    /*
     * Deleting page
     */
    function remove($id)
    {
        $page = $this->Page_model->get_page($id);

        // check if the page exists before trying to delete it
        if(isset($page['id']))
        {
            $this->Page_model->delete_page($id);
            redirect('pages/index');
        }
        else
            show_error('The page you are trying to delete does not exist.');
    }
    
}
