<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vh_usr_model');
    }

    function index($paganame)
    {
echo $paganame; exit;
		
        $this->load->view('home');
    }

}
